In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

In [18]:
PROJECT_ROOT = Path.cwd().parent.parent.parent.parent.parent
print(PROJECT_ROOT)
DATASET_PATH = PROJECT_ROOT / "PROJECTS" / "RETAIL COMPANY PROJECT" / "DATASET" / "customer_shopping_behavior.csv"
print(DATASET_PATH)

c:\Users\IGO\OneDrive\Bureau
c:\Users\IGO\OneDrive\Bureau\PROJECTS\RETAIL COMPANY PROJECT\DATASET\customer_shopping_behavior.csv

In [20]:
dataset = pd.read_csv(DATASET_PATH)
df = dataset.copy()
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [22]:
df.columns=df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.rename(columns={"purchase_amount_(usd)":"purchase_amount"},inplace=True)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [23]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,3900.0,NaN,NaN,NaN,1950.5,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
age,3900.0,NaN,NaN,NaN,44.068462,15.207589,18.0,31.0,44.0,57.0,70.0
gender,3900,2,Male,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
item_purchased,3900,25,Blouse,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,3900,4,Clothing,1737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_amount,3900.0,NaN,NaN,NaN,59.764359,23.685392,20.0,39.0,60.0,81.0,100.0
location,3900,50,Montana,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
size,3900,4,M,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
color,3900,25,Olive,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
season,3900,4,Spring,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_rating,3863.0,NaN,NaN,NaN,3.750065,0.716983,2.5,3.1,3.8,4.4,5.0
subscription_status,3900,2,No,2847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipping_type,3900,6,Free Shipping,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discount_applied,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_code_used,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
previous_purchases,3900.0,NaN,NaN,NaN,25.351538,14.447125,1.0,13.0,25.0,38.0,50.0
payment_method,3900,6,PayPal,677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
frequency_of_purchases,3900,7,Every 3 Months,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [25]:
df["review_rating"].describe()

count    3863.000000
mean        3.750065
std         0.716983
min         2.500000
25%         3.100000
50%         3.800000
75%         4.400000
max         5.000000
Name: review_rating, dtype: float64

In [26]:
df["review_rating"] = df.groupby("category")["review_rating"].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [27]:
df["age"].describe()

count    3900.000000
mean       44.068462
std        15.207589
min        18.000000
25%        31.000000
50%        44.000000
75%        57.000000
max        70.000000
Name: age, dtype: float64

In [28]:
def age_category(age):
    if age < 18:
        return "Child"
    elif age < 30:
        return "Young Adult"
    elif age < 45:
        return "Adult"
    elif age < 60:
        return "Senior Adult"
    else:
        return "Elder"

df["age_group"] = df["age"].apply(age_category)

df[["age", "age_group"]].head(10)

   age     age_group
0   55  Senior Adult
1   19   Young Adult
2   50  Senior Adult
3   21   Young Adult
4   45  Senior Adult
5   46  Senior Adult
6   63         Elder
7   27   Young Adult
8   26   Young Adult
9   57  Senior Adult

In [29]:
df["frequency_of_purchases"].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [36]:
frequency_mapping = {

    "Weekly" : 7,
    "Fortnightly" : 14,
    "Biweekly" : 14,
    "Monthly" : 30,
    "Quarterly" : 90, 
    "Every 3 Months" : 90,
    "Annually" : 365
}


df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)


df[["frequency_of_purchases", "purchase_frequency_days"]].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                     14.0
1            Fortnightly                     14.0
2                 Weekly                      7.0
3                 Weekly                      7.0
4               Annually                    365.0
5                 Weekly                      7.0
6              Quarterly                     90.0
7                 Weekly                      7.0
8               Annually                    365.0
9              Quarterly                     90.0

In [31]:
df[["discount_applied","promo_code_used"]].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [32]:
(df["discount_applied"] == df["promo_code_used"]).all()

np.True_

In [33]:
df=df.drop(columns=["promo_code_used"])

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [36]:
import pyodbc
from sqlalchemy import create_engine, text

# Local SQL Server Express
server = r".\SQLEXPRESS"
database = "customer_shopping_behavior"

try:
    conn = pyodbc.connect(
        r"DRIVER={ODBC Driver 17 for SQL Server};"
        f"SERVER={server};"
        f"DATABASE={database};"
        "Trusted_Connection=yes;"
    )
    cursor = conn.cursor()
    cursor.execute("SELECT 1")
    print("Connection successful:", cursor.fetchone())
except Exception as e:
    print("Connection failed:", e)



# 3️⃣ Connect to SQL Server
# ---------------------------
server = r".\SQLEXPRESS"
database = "customer_shopping_behavior"

# Wrap pyodbc connection in SQLAlchemy engine
conn_str = (
    r"mssql+pyodbc://@.\SQLEXPRESS/customer_shopping_behavior?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)
engine = create_engine(conn_str)

# ---------------------------
# 4️⃣ Upload DataFrame to SQL Server
# ---------------------------
df.to_sql(
    name="TransformedSuperstore",  # Table name in SQL Server
    con=engine,
    if_exists="replace",           # replace / append / fail
    index=False
    
)

# ---------------------------
# 5️⃣ Verify Upload
# ---------------------------
with engine.connect() as conn:
    result = conn.execute(text("SELECT TOP 10 * FROM TransformedSuperstore"))
    for row in result:
        print(row)

ModuleNotFoundError: No module named 'pyodbc'